gx.evt.autoSkip = false;
gx.define('version1.webpanel1', false, function () {
   this.ServerClass =  "version1.webpanel1" ;
   this.PackageName =  "GeneXus.Programs" ;
   this.setObjectType("web");
   this.hasEnterEvent = false;
   this.skipOnEnter = false;
   this.autoRefresh = true;
   this.fullAjax = true;
   this.supportAjaxEvents =  true ;
   this.ajaxSecurityToken =  true ;
   this.SetStandaloneVars=function()
   {
   };
   this.e121h2_client=function()
   {
      return this.executeServerEvent("ENTER", true, null, false, false);
   };
   this.e131h2_client=function()
   {
      return this.executeServerEvent("CANCEL", true, null, false, false);
   };
   this.GXValidFnc = [];
   var GXValidFnc = this.GXValidFnc ;
   this.GXCtrlIds=[2,3,4,5,7,9,10,12,14,16,17,19,21,22,24,25];
   this.GXLastCtrlId =25;
   this.QUERYVIEWER1Container = gx.uc.getNew(this, 6, 0, "QueryViewer", "QUERYVIEWER1Container", "Queryviewer1", "QUERYVIEWER1");
   var QUERYVIEWER1Container = this.QUERYVIEWER1Container;
   QUERYVIEWER1Container.setProp("Enabled", "Enabled", true, "boolean");
   QUERYVIEWER1Container.setProp("ObjectId", "Objectid", "7", "str");
   QUERYVIEWER1Container.setProp("ObjectType", "Objecttype", "Query", "str");
   QUERYVIEWER1Container.setProp("QueryInfo", "Queryinfo", "", "char");
   QUERYVIEWER1Container.setProp("IsExternalQuery", "Isexternalquery", false, "boolean");
   QUERYVIEWER1Container.setProp("ExternalQueryResult", "Externalqueryresult", "", "char");
   QUERYVIEWER1Container.setProp("ObjectInfo", "Objectinfo", "", "char");
   QUERYVIEWER1Container.addV2CFunction('AV7Axes', "vAXES", 'SetAxes');
   QUERYVIEWER1Container.addC2VFunction(function(UC) { UC.ParentObject.AV7Axes=UC.GetAxes();gx.fn.setControlValue("vAXES",UC.ParentObject.AV7Axes); });
   QUERYVIEWER1Container.setProp("AllowChangeAxesOrder", "Allowchangeaxesorder", false, "bool");
   QUERYVIEWER1Container.addV2CFunction('AV5Parameters', "vPARAMETERS", 'SetParameters');
   QUERYVIEWER1Container.addC2VFunction(function(UC) { UC.ParentObject.AV5Parameters=UC.GetParameters();gx.fn.setControlValue("vPARAMETERS",UC.ParentObject.AV5Parameters); });
   QUERYVIEWER1Container.setProp("ObjectName", "Objectname", "QKPICantCli", "str");
   QUERYVIEWER1Container.setProp("Object", "Objectcall", "", "str");
   QUERYVIEWER1Container.setProp("Class", "Class", "QueryViewer", "str");
   QUERYVIEWER1Container.setProp("ShrinkToFit", "Shrinktofit", false, "boolean");
   QUERYVIEWER1Container.setProp("AutoResize", "Autoresize", false, "bool");
   QUERYVIEWER1Container.setProp("AutoResizeType", "Autoresizetype", "", "char");
   QUERYVIEWER1Container.setProp("Width", "Width", "100%", "str");
   QUERYVIEWER1Container.setProp("Height", "Height", "100%", "str");
   QUERYVIEWER1Container.setProp("Axes Selectors", "Showaxesselectors", "", "char");
   QUERYVIEWER1Container.setProp("FontFamily", "Fontfamily", "", "char");
   QUERYVIEWER1Container.setProp("FontSize", "Fontsize", '', "int");
   QUERYVIEWER1Container.setProp("FontColor", "Fontcolor", '', "int");
   QUERYVIEWER1Container.setProp("AutoRefreshGroup", "Autorefreshgroup", "", "str");
   QUERYVIEWER1Container.setProp("DisableColumnSort", "Disablecolumnsort", false, "bool");
   QUERYVIEWER1Container.setProp("AllowSelection", "Allowselection", false, "bool");
   QUERYVIEWER1Container.setProp("RememberLayout", "Rememberlayout", true, "bool");
   QUERYVIEWER1Container.setProp("ExportToXML", "Exporttoxml", true, "bool");
   QUERYVIEWER1Container.setProp("ExportToHTML", "Exporttohtml", true, "bool");
   QUERYVIEWER1Container.setProp("ExportToXLS", "Exporttoxls", true, "bool");
   QUERYVIEWER1Container.setProp("ExportToXLSX", "Exporttoxlsx", true, "bool");
   QUERYVIEWER1Container.setProp("ExportToPDF", "Exporttopdf", true, "bool");
   QUERYVIEWER1Container.setProp("Type", "Type", "Card", "str");
   QUERYVIEWER1Container.setProp("ShowDataAs", "Showdataas", "Values", "str");
   QUERYVIEWER1Container.setProp("Orientation", "Orientation", "Horizontal", "str");
   QUERYVIEWER1Container.setProp("IncludeTrend", "Includetrend", false, "bool");
   QUERYVIEWER1Container.setProp("TrendPeriod", "Trendperiod", "", "char");
   QUERYVIEWER1Container.setProp("IncludeSparkline", "Includesparkline", false, "bool");
   QUERYVIEWER1Container.setProp("IncludeMaxAndMin", "Includemaxandmin", false, "bool");
   QUERYVIEWER1Container.setProp("ChartType", "Charttype", "", "char");
   QUERYVIEWER1Container.setProp("Title", "Title", "", "char");
   QUERYVIEWER1Container.setProp("PlotSeries", "Plotseries", "", "char");
   QUERYVIEWER1Container.setProp("ShowValues", "Showvalues", false, "boolean");
   QUERYVIEWER1Container.setProp("XAxisLabels", "Xaxislabels", "", "char");
   QUERYVIEWER1Container.setProp("XAxisIntersectionAtZero", "Xaxisintersectionatzero", false, "boolean");
   QUERYVIEWER1Container.setProp("XAxisTitle", "Xaxistitle", "", "char");
   QUERYVIEWER1Container.setProp("YAxisTitle", "Yaxistitle", "", "char");
   QUERYVIEWER1Container.setProp("Paging", "Paging", false, "boolean");
   QUERYVIEWER1Container.setProp("PageSize", "Pagesize", '', "int");
   QUERYVIEWER1Container.setProp("CurrentPage", "Currentpage", '', "int");
   QUERYVIEWER1Container.setProp("ShowDataLabelsIn", "Showdatalabelsin", "", "char");
   QUERYVIEWER1Container.addV2CFunction('AV13ItemClickData', "vITEMCLICKDATA", 'SetItemClickData');
   QUERYVIEWER1Container.addC2VFunction(function(UC) { UC.ParentObject.AV13ItemClickData=UC.GetItemClickData();gx.fn.setControlValue("vITEMCLICKDATA",UC.ParentObject.AV13ItemClickData); });
   QUERYVIEWER1Container.addV2CFunction('AV14ItemDoubleClickData', "vITEMDOUBLECLICKDATA", 'SetItemDoubleClickData');
   QUERYVIEWER1Container.addC2VFunction(function(UC) { UC.ParentObject.AV14ItemDoubleClickData=UC.GetItemDoubleClickData();gx.fn.setControlValue("vITEMDOUBLECLICKDATA",UC.ParentObject.AV14ItemDoubleClickData); });
   QUERYVIEWER1Container.addV2CFunction('AV9DragAndDropData', "vDRAGANDDROPDATA", 'SetDragAndDropData');
   QUERYVIEWER1Container.addC2VFunction(function(UC) { UC.ParentObject.AV9DragAndDropData=UC.GetDragAndDropData();gx.fn.setControlValue("vDRAGANDDROPDATA",UC.ParentObject.AV9DragAndDropData); });
   QUERYVIEWER1Container.addV2CFunction('AV12FilterChangedData', "vFILTERCHANGEDDATA", 'SetFilterChangedData');
   QUERYVIEWER1Container.addC2VFunction(function(UC) { UC.ParentObject.AV12FilterChangedData=UC.GetFilterChangedData();gx.fn.setControlValue("vFILTERCHANGEDDATA",UC.ParentObject.AV12FilterChangedData); });
   QUERYVIEWER1Container.addV2CFunction('AV10ItemExpandData', "vITEMEXPANDDATA", 'SetItemExpandData');
   QUERYVIEWER1Container.addC2VFunction(function(UC) { UC.ParentObject.AV10ItemExpandData=UC.GetItemExpandData();gx.fn.setControlValue("vITEMEXPANDDATA",UC.ParentObject.AV10ItemExpandData); });
   QUERYVIEWER1Container.addV2CFunction('AV11ItemCollapseData', "vITEMCOLLAPSEDATA", 'SetItemCollapseData');
   QUERYVIEWER1Container.addC2VFunction(function(UC) { UC.ParentObject.AV11ItemCollapseData=UC.GetItemCollapseData();gx.fn.setControlValue("vITEMCOLLAPSEDATA",UC.ParentObject.AV11ItemCollapseData); });
   QUERYVIEWER1Container.setProp("AppSettings", "Appsettings", "", "char");
   QUERYVIEWER1Container.setProp("AvoidAutomaticShow", "Avoidautomaticshow", false, "boolean");
   QUERYVIEWER1Container.setProp("ExecuteShow", "Executeshow", false, "boolean");
   QUERYVIEWER1Container.setProp("ServiceUrl", "Serviceurl", "", "char");
   QUERYVIEWER1Container.setProp("GenType", "Gentype", "", "char");
   QUERYVIEWER1Container.setProp("DesignRenderOutputType", "Designrenderoutputtype", "", "char");
   QUERYVIEWER1Container.setProp("Visible", "Visible", true, "bool");
   QUERYVIEWER1Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(QUERYVIEWER1Container);
   this.QUERYVIEWER2Container = gx.uc.getNew(this, 11, 0, "QueryViewer", "QUERYVIEWER2Container", "Queryviewer2", "QUERYVIEWER2");
   var QUERYVIEWER2Container = this.QUERYVIEWER2Container;
   QUERYVIEWER2Container.setProp("Enabled", "Enabled", true, "boolean");
   QUERYVIEWER2Container.setProp("ObjectId", "Objectid", "5", "str");
   QUERYVIEWER2Container.setProp("ObjectType", "Objecttype", "Query", "str");
   QUERYVIEWER2Container.setProp("QueryInfo", "Queryinfo", "", "char");
   QUERYVIEWER2Container.setProp("IsExternalQuery", "Isexternalquery", false, "boolean");
   QUERYVIEWER2Container.setProp("ExternalQueryResult", "Externalqueryresult", "", "char");
   QUERYVIEWER2Container.setProp("ObjectInfo", "Objectinfo", "", "char");
   QUERYVIEWER2Container.addV2CFunction('AV7Axes', "vAXES", 'SetAxes');
   QUERYVIEWER2Container.addC2VFunction(function(UC) { UC.ParentObject.AV7Axes=UC.GetAxes();gx.fn.setControlValue("vAXES",UC.ParentObject.AV7Axes); });
   QUERYVIEWER2Container.setProp("AllowChangeAxesOrder", "Allowchangeaxesorder", false, "bool");
   QUERYVIEWER2Container.addV2CFunction('AV5Parameters', "vPARAMETERS", 'SetParameters');
   QUERYVIEWER2Container.addC2VFunction(function(UC) { UC.ParentObject.AV5Parameters=UC.GetParameters();gx.fn.setControlValue("vPARAMETERS",UC.ParentObject.AV5Parameters); });
   QUERYVIEWER2Container.setProp("ObjectName", "Objectname", "QPieChartCli", "str");
   QUERYVIEWER2Container.setProp("Object", "Objectcall", "", "str");
   QUERYVIEWER2Container.setProp("Class", "Class", "QueryViewer", "str");
   QUERYVIEWER2Container.setProp("ShrinkToFit", "Shrinktofit", false, "boolean");
   QUERYVIEWER2Container.setProp("AutoResize", "Autoresize", false, "boolean");
   QUERYVIEWER2Container.setProp("AutoResizeType", "Autoresizetype", "", "char");
   QUERYVIEWER2Container.setProp("Width", "Width", "100%", "str");
   QUERYVIEWER2Container.setProp("Height", "Height", "100%", "str");
   QUERYVIEWER2Container.setProp("Axes Selectors", "Showaxesselectors", "", "char");
   QUERYVIEWER2Container.setProp("FontFamily", "Fontfamily", "", "char");
   QUERYVIEWER2Container.setProp("FontSize", "Fontsize", '', "int");
   QUERYVIEWER2Container.setProp("FontColor", "Fontcolor", '', "int");
   QUERYVIEWER2Container.setProp("AutoRefreshGroup", "Autorefreshgroup", "", "str");
   QUERYVIEWER2Container.setProp("DisableColumnSort", "Disablecolumnsort", false, "boolean");
   QUERYVIEWER2Container.setProp("AllowSelection", "Allowselection", false, "bool");
   QUERYVIEWER2Container.setProp("RememberLayout", "Rememberlayout", true, "bool");
   QUERYVIEWER2Container.setProp("ExportToXML", "Exporttoxml", true, "bool");
   QUERYVIEWER2Container.setProp("ExportToHTML", "Exporttohtml", true, "bool");
   QUERYVIEWER2Container.setProp("ExportToXLS", "Exporttoxls", true, "bool");
   QUERYVIEWER2Container.setProp("ExportToXLSX", "Exporttoxlsx", true, "bool");
   QUERYVIEWER2Container.setProp("ExportToPDF", "Exporttopdf", true, "bool");
   QUERYVIEWER2Container.setProp("Type", "Type", "Chart", "str");
   QUERYVIEWER2Container.setProp("ShowDataAs", "Showdataas", "", "char");
   QUERYVIEWER2Container.setProp("Orientation", "Orientation", "", "char");
   QUERYVIEWER2Container.setProp("IncludeTrend", "Includetrend", false, "boolean");
   QUERYVIEWER2Container.setProp("TrendPeriod", "Trendperiod", "", "char");
   QUERYVIEWER2Container.setProp("IncludeSparkline", "Includesparkline", false, "boolean");
   QUERYVIEWER2Container.setProp("IncludeMaxAndMin", "Includemaxandmin", false, "boolean");
   QUERYVIEWER2Container.setProp("ChartType", "Charttype", "Pie", "str");
   QUERYVIEWER2Container.setProp("Title", "Title", "Clientes Fidelizados", "str");
   QUERYVIEWER2Container.setProp("PlotSeries", "Plotseries", "InTheSameChart", "str");
   QUERYVIEWER2Container.setProp("ShowValues", "Showvalues", true, "bool");
   QUERYVIEWER2Container.setProp("XAxisLabels", "Xaxislabels", "Horizontally", "str");
   QUERYVIEWER2Container.setProp("XAxisIntersectionAtZero", "Xaxisintersectionatzero", false, "bool");
   QUERYVIEWER2Container.setProp("XAxisTitle", "Xaxistitle", "RFM", "str");
   QUERYVIEWER2Container.setProp("YAxisTitle", "Yaxistitle", "Clientes", "str");
   QUERYVIEWER2Container.setProp("Paging", "Paging", false, "boolean");
   QUERYVIEWER2Container.setProp("PageSize", "Pagesize", '', "int");
   QUERYVIEWER2Container.setProp("CurrentPage", "Currentpage", '', "int");
   QUERYVIEWER2Container.setProp("ShowDataLabelsIn", "Showdatalabelsin", "", "char");
   QUERYVIEWER2Container.addV2CFunction('AV13ItemClickData', "vITEMCLICKDATA", 'SetItemClickData');
   QUERYVIEWER2Container.addC2VFunction(function(UC) { UC.ParentObject.AV13ItemClickData=UC.GetItemClickData();gx.fn.setControlValue("vITEMCLICKDATA",UC.ParentObject.AV13ItemClickData); });
   QUERYVIEWER2Container.addV2CFunction('AV14ItemDoubleClickData', "vITEMDOUBLECLICKDATA", 'SetItemDoubleClickData');
   QUERYVIEWER2Container.addC2VFunction(function(UC) { UC.ParentObject.AV14ItemDoubleClickData=UC.GetItemDoubleClickData();gx.fn.setControlValue("vITEMDOUBLECLICKDATA",UC.ParentObject.AV14ItemDoubleClickData); });
   QUERYVIEWER2Container.addV2CFunction('AV9DragAndDropData', "vDRAGANDDROPDATA", 'SetDragAndDropData');
   QUERYVIEWER2Container.addC2VFunction(function(UC) { UC.ParentObject.AV9DragAndDropData=UC.GetDragAndDropData();gx.fn.setControlValue("vDRAGANDDROPDATA",UC.ParentObject.AV9DragAndDropData); });
   QUERYVIEWER2Container.addV2CFunction('AV12FilterChangedData', "vFILTERCHANGEDDATA", 'SetFilterChangedData');
   QUERYVIEWER2Container.addC2VFunction(function(UC) { UC.ParentObject.AV12FilterChangedData=UC.GetFilterChangedData();gx.fn.setControlValue("vFILTERCHANGEDDATA",UC.ParentObject.AV12FilterChangedData); });
   QUERYVIEWER2Container.addV2CFunction('AV10ItemExpandData', "vITEMEXPANDDATA", 'SetItemExpandData');
   QUERYVIEWER2Container.addC2VFunction(function(UC) { UC.ParentObject.AV10ItemExpandData=UC.GetItemExpandData();gx.fn.setControlValue("vITEMEXPANDDATA",UC.ParentObject.AV10ItemExpandData); });
   QUERYVIEWER2Container.addV2CFunction('AV11ItemCollapseData', "vITEMCOLLAPSEDATA", 'SetItemCollapseData');
   QUERYVIEWER2Container.addC2VFunction(function(UC) { UC.ParentObject.AV11ItemCollapseData=UC.GetItemCollapseData();gx.fn.setControlValue("vITEMCOLLAPSEDATA",UC.ParentObject.AV11ItemCollapseData); });
   QUERYVIEWER2Container.setProp("AppSettings", "Appsettings", "", "char");
   QUERYVIEWER2Container.setProp("AvoidAutomaticShow", "Avoidautomaticshow", false, "boolean");
   QUERYVIEWER2Container.setProp("ExecuteShow", "Executeshow", false, "boolean");
   QUERYVIEWER2Container.setProp("ServiceUrl", "Serviceurl", "", "char");
   QUERYVIEWER2Container.setProp("GenType", "Gentype", "", "char");
   QUERYVIEWER2Container.setProp("DesignRenderOutputType", "Designrenderoutputtype", "", "char");
   QUERYVIEWER2Container.setProp("Visible", "Visible", true, "bool");
   QUERYVIEWER2Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(QUERYVIEWER2Container);
   this.QUERYVIEWER3Container = gx.uc.getNew(this, 13, 0, "QueryViewer", "QUERYVIEWER3Container", "Queryviewer3", "QUERYVIEWER3");
   var QUERYVIEWER3Container = this.QUERYVIEWER3Container;
   QUERYVIEWER3Container.setProp("Enabled", "Enabled", true, "boolean");
   QUERYVIEWER3Container.setProp("ObjectId", "Objectid", "9", "str");
   QUERYVIEWER3Container.setProp("ObjectType", "Objecttype", "Query", "str");
   QUERYVIEWER3Container.setProp("QueryInfo", "Queryinfo", "", "char");
   QUERYVIEWER3Container.setProp("IsExternalQuery", "Isexternalquery", false, "boolean");
   QUERYVIEWER3Container.setProp("ExternalQueryResult", "Externalqueryresult", "", "char");
   QUERYVIEWER3Container.setProp("ObjectInfo", "Objectinfo", "", "char");
   QUERYVIEWER3Container.addV2CFunction('AV7Axes', "vAXES", 'SetAxes');
   QUERYVIEWER3Container.addC2VFunction(function(UC) { UC.ParentObject.AV7Axes=UC.GetAxes();gx.fn.setControlValue("vAXES",UC.ParentObject.AV7Axes); });
   QUERYVIEWER3Container.setProp("AllowChangeAxesOrder", "Allowchangeaxesorder", false, "bool");
   QUERYVIEWER3Container.addV2CFunction('AV5Parameters', "vPARAMETERS", 'SetParameters');
   QUERYVIEWER3Container.addC2VFunction(function(UC) { UC.ParentObject.AV5Parameters=UC.GetParameters();gx.fn.setControlValue("vPARAMETERS",UC.ParentObject.AV5Parameters); });
   QUERYVIEWER3Container.setProp("ObjectName", "Objectname", "QPieChartFac", "str");
   QUERYVIEWER3Container.setProp("Object", "Objectcall", "", "str");
   QUERYVIEWER3Container.setProp("Class", "Class", "QueryViewer", "str");
   QUERYVIEWER3Container.setProp("ShrinkToFit", "Shrinktofit", false, "boolean");
   QUERYVIEWER3Container.setProp("AutoResize", "Autoresize", false, "boolean");
   QUERYVIEWER3Container.setProp("AutoResizeType", "Autoresizetype", "", "char");
   QUERYVIEWER3Container.setProp("Width", "Width", "100%", "str");
   QUERYVIEWER3Container.setProp("Height", "Height", "100%", "str");
   QUERYVIEWER3Container.setProp("Axes Selectors", "Showaxesselectors", "", "char");
   QUERYVIEWER3Container.setProp("FontFamily", "Fontfamily", "", "char");
   QUERYVIEWER3Container.setProp("FontSize", "Fontsize", '', "int");
   QUERYVIEWER3Container.setProp("FontColor", "Fontcolor", '', "int");
   QUERYVIEWER3Container.setProp("AutoRefreshGroup", "Autorefreshgroup", "", "str");
   QUERYVIEWER3Container.setProp("DisableColumnSort", "Disablecolumnsort", false, "boolean");
   QUERYVIEWER3Container.setProp("AllowSelection", "Allowselection", false, "bool");
   QUERYVIEWER3Container.setProp("RememberLayout", "Rememberlayout", true, "bool");
   QUERYVIEWER3Container.setProp("ExportToXML", "Exporttoxml", true, "bool");
   QUERYVIEWER3Container.setProp("ExportToHTML", "Exporttohtml", true, "bool");
   QUERYVIEWER3Container.setProp("ExportToXLS", "Exporttoxls", true, "bool");
   QUERYVIEWER3Container.setProp("ExportToXLSX", "Exporttoxlsx", true, "bool");
   QUERYVIEWER3Container.setProp("ExportToPDF", "Exporttopdf", true, "bool");
   QUERYVIEWER3Container.setProp("Type", "Type", "Chart", "str");
   QUERYVIEWER3Container.setProp("ShowDataAs", "Showdataas", "", "char");
   QUERYVIEWER3Container.setProp("Orientation", "Orientation", "", "char");
   QUERYVIEWER3Container.setProp("IncludeTrend", "Includetrend", false, "boolean");
   QUERYVIEWER3Container.setProp("TrendPeriod", "Trendperiod", "", "char");
   QUERYVIEWER3Container.setProp("IncludeSparkline", "Includesparkline", false, "boolean");
   QUERYVIEWER3Container.setProp("IncludeMaxAndMin", "Includemaxandmin", false, "boolean");
   QUERYVIEWER3Container.setProp("ChartType", "Charttype", "Pie", "str");
   QUERYVIEWER3Container.setProp("Title", "Title", "Facturación", "str");
   QUERYVIEWER3Container.setProp("PlotSeries", "Plotseries", "InTheSameChart", "str");
   QUERYVIEWER3Container.setProp("ShowValues", "Showvalues", true, "bool");
   QUERYVIEWER3Container.setProp("XAxisLabels", "Xaxislabels", "Horizontally", "str");
   QUERYVIEWER3Container.setProp("XAxisIntersectionAtZero", "Xaxisintersectionatzero", true, "bool");
   QUERYVIEWER3Container.setProp("XAxisTitle", "Xaxistitle", "RFM", "str");
   QUERYVIEWER3Container.setProp("YAxisTitle", "Yaxistitle", "Clientes", "str");
   QUERYVIEWER3Container.setProp("Paging", "Paging", false, "boolean");
   QUERYVIEWER3Container.setProp("PageSize", "Pagesize", '', "int");
   QUERYVIEWER3Container.setProp("CurrentPage", "Currentpage", '', "int");
   QUERYVIEWER3Container.setProp("ShowDataLabelsIn", "Showdatalabelsin", "", "char");
   QUERYVIEWER3Container.addV2CFunction('AV13ItemClickData', "vITEMCLICKDATA", 'SetItemClickData');
   QUERYVIEWER3Container.addC2VFunction(function(UC) { UC.ParentObject.AV13ItemClickData=UC.GetItemClickData();gx.fn.setControlValue("vITEMCLICKDATA",UC.ParentObject.AV13ItemClickData); });
   QUERYVIEWER3Container.addV2CFunction('AV14ItemDoubleClickData', "vITEMDOUBLECLICKDATA", 'SetItemDoubleClickData');
   QUERYVIEWER3Container.addC2VFunction(function(UC) { UC.ParentObject.AV14ItemDoubleClickData=UC.GetItemDoubleClickData();gx.fn.setControlValue("vITEMDOUBLECLICKDATA",UC.ParentObject.AV14ItemDoubleClickData); });
   QUERYVIEWER3Container.addV2CFunction('AV9DragAndDropData', "vDRAGANDDROPDATA", 'SetDragAndDropData');
   QUERYVIEWER3Container.addC2VFunction(function(UC) { UC.ParentObject.AV9DragAndDropData=UC.GetDragAndDropData();gx.fn.setControlValue("vDRAGANDDROPDATA",UC.ParentObject.AV9DragAndDropData); });
   QUERYVIEWER3Container.addV2CFunction('AV12FilterChangedData', "vFILTERCHANGEDDATA", 'SetFilterChangedData');
   QUERYVIEWER3Container.addC2VFunction(function(UC) { UC.ParentObject.AV12FilterChangedData=UC.GetFilterChangedData();gx.fn.setControlValue("vFILTERCHANGEDDATA",UC.ParentObject.AV12FilterChangedData); });
   QUERYVIEWER3Container.addV2CFunction('AV10ItemExpandData', "vITEMEXPANDDATA", 'SetItemExpandData');
   QUERYVIEWER3Container.addC2VFunction(function(UC) { UC.ParentObject.AV10ItemExpandData=UC.GetItemExpandData();gx.fn.setControlValue("vITEMEXPANDDATA",UC.ParentObject.AV10ItemExpandData); });
   QUERYVIEWER3Container.addV2CFunction('AV11ItemCollapseData', "vITEMCOLLAPSEDATA", 'SetItemCollapseData');
   QUERYVIEWER3Container.addC2VFunction(function(UC) { UC.ParentObject.AV11ItemCollapseData=UC.GetItemCollapseData();gx.fn.setControlValue("vITEMCOLLAPSEDATA",UC.ParentObject.AV11ItemCollapseData); });
   QUERYVIEWER3Container.setProp("AppSettings", "Appsettings", "", "char");
   QUERYVIEWER3Container.setProp("AvoidAutomaticShow", "Avoidautomaticshow", false, "boolean");
   QUERYVIEWER3Container.setProp("ExecuteShow", "Executeshow", false, "boolean");
   QUERYVIEWER3Container.setProp("ServiceUrl", "Serviceurl", "", "char");
   QUERYVIEWER3Container.setProp("GenType", "Gentype", "", "char");
   QUERYVIEWER3Container.setProp("DesignRenderOutputType", "Designrenderoutputtype", "", "char");
   QUERYVIEWER3Container.setProp("Visible", "Visible", true, "bool");
   QUERYVIEWER3Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(QUERYVIEWER3Container);
   this.QUERYVIEWER4Container = gx.uc.getNew(this, 15, 0, "QueryViewer", "QUERYVIEWER4Container", "Queryviewer4", "QUERYVIEWER4");
   var QUERYVIEWER4Container = this.QUERYVIEWER4Container;
   QUERYVIEWER4Container.setProp("Enabled", "Enabled", true, "boolean");
   QUERYVIEWER4Container.setProp("ObjectId", "Objectid", "12", "str");
   QUERYVIEWER4Container.setProp("ObjectType", "Objecttype", "Query", "str");
   QUERYVIEWER4Container.setProp("QueryInfo", "Queryinfo", "", "char");
   QUERYVIEWER4Container.setProp("IsExternalQuery", "Isexternalquery", false, "boolean");
   QUERYVIEWER4Container.setProp("ExternalQueryResult", "Externalqueryresult", "", "char");
   QUERYVIEWER4Container.setProp("ObjectInfo", "Objectinfo", "", "char");
   QUERYVIEWER4Container.addV2CFunction('AV7Axes', "vAXES", 'SetAxes');
   QUERYVIEWER4Container.addC2VFunction(function(UC) { UC.ParentObject.AV7Axes=UC.GetAxes();gx.fn.setControlValue("vAXES",UC.ParentObject.AV7Axes); });
   QUERYVIEWER4Container.setProp("AllowChangeAxesOrder", "Allowchangeaxesorder", false, "bool");
   QUERYVIEWER4Container.addV2CFunction('AV5Parameters', "vPARAMETERS", 'SetParameters');
   QUERYVIEWER4Container.addC2VFunction(function(UC) { UC.ParentObject.AV5Parameters=UC.GetParameters();gx.fn.setControlValue("vPARAMETERS",UC.ParentObject.AV5Parameters); });
   QUERYVIEWER4Container.setProp("ObjectName", "Objectname", "QPieChartTks", "str");
   QUERYVIEWER4Container.setProp("Object", "Objectcall", "", "str");
   QUERYVIEWER4Container.setProp("Class", "Class", "QueryViewer", "str");
   QUERYVIEWER4Container.setProp("ShrinkToFit", "Shrinktofit", false, "boolean");
   QUERYVIEWER4Container.setProp("AutoResize", "Autoresize", false, "boolean");
   QUERYVIEWER4Container.setProp("AutoResizeType", "Autoresizetype", "", "char");
   QUERYVIEWER4Container.setProp("Width", "Width", "100%", "str");
   QUERYVIEWER4Container.setProp("Height", "Height", "100%", "str");
   QUERYVIEWER4Container.setProp("Axes Selectors", "Showaxesselectors", "", "char");
   QUERYVIEWER4Container.setProp("FontFamily", "Fontfamily", "", "char");
   QUERYVIEWER4Container.setProp("FontSize", "Fontsize", '', "int");
   QUERYVIEWER4Container.setProp("FontColor", "Fontcolor", '', "int");
   QUERYVIEWER4Container.setProp("AutoRefreshGroup", "Autorefreshgroup", "", "str");
   QUERYVIEWER4Container.setProp("DisableColumnSort", "Disablecolumnsort", false, "boolean");
   QUERYVIEWER4Container.setProp("AllowSelection", "Allowselection", false, "bool");
   QUERYVIEWER4Container.setProp("RememberLayout", "Rememberlayout", true, "bool");
   QUERYVIEWER4Container.setProp("ExportToXML", "Exporttoxml", true, "bool");
   QUERYVIEWER4Container.setProp("ExportToHTML", "Exporttohtml", true, "bool");
   QUERYVIEWER4Container.setProp("ExportToXLS", "Exporttoxls", true, "bool");
   QUERYVIEWER4Container.setProp("ExportToXLSX", "Exporttoxlsx", true, "bool");
   QUERYVIEWER4Container.setProp("ExportToPDF", "Exporttopdf", true, "bool");
   QUERYVIEWER4Container.setProp("Type", "Type", "Chart", "str");
   QUERYVIEWER4Container.setProp("ShowDataAs", "Showdataas", "", "char");
   QUERYVIEWER4Container.setProp("Orientation", "Orientation", "", "char");
   QUERYVIEWER4Container.setProp("IncludeTrend", "Includetrend", false, "boolean");
   QUERYVIEWER4Container.setProp("TrendPeriod", "Trendperiod", "", "char");
   QUERYVIEWER4Container.setProp("IncludeSparkline", "Includesparkline", false, "boolean");
   QUERYVIEWER4Container.setProp("IncludeMaxAndMin", "Includemaxandmin", false, "boolean");
   QUERYVIEWER4Container.setProp("ChartType", "Charttype", "Pie", "str");
   QUERYVIEWER4Container.setProp("Title", "Title", "Tickets", "str");
   QUERYVIEWER4Container.setProp("PlotSeries", "Plotseries", "InTheSameChart", "str");
   QUERYVIEWER4Container.setProp("ShowValues", "Showvalues", true, "bool");
   QUERYVIEWER4Container.setProp("XAxisLabels", "Xaxislabels", "Horizontally", "str");
   QUERYVIEWER4Container.setProp("XAxisIntersectionAtZero", "Xaxisintersectionatzero", true, "bool");
   QUERYVIEWER4Container.setProp("XAxisTitle", "Xaxistitle", "RFM", "str");
   QUERYVIEWER4Container.setProp("YAxisTitle", "Yaxistitle", "Clientes", "str");
   QUERYVIEWER4Container.setProp("Paging", "Paging", false, "boolean");
   QUERYVIEWER4Container.setProp("PageSize", "Pagesize", '', "int");
   QUERYVIEWER4Container.setProp("CurrentPage", "Currentpage", '', "int");
   QUERYVIEWER4Container.setProp("ShowDataLabelsIn", "Showdatalabelsin", "", "char");
   QUERYVIEWER4Container.addV2CFunction('AV13ItemClickData', "vITEMCLICKDATA", 'SetItemClickData');
   QUERYVIEWER4Container.addC2VFunction(function(UC) { UC.ParentObject.AV13ItemClickData=UC.GetItemClickData();gx.fn.setControlValue("vITEMCLICKDATA",UC.ParentObject.AV13ItemClickData); });
   QUERYVIEWER4Container.addV2CFunction('AV14ItemDoubleClickData', "vITEMDOUBLECLICKDATA", 'SetItemDoubleClickData');
   QUERYVIEWER4Container.addC2VFunction(function(UC) { UC.ParentObject.AV14ItemDoubleClickData=UC.GetItemDoubleClickData();gx.fn.setControlValue("vITEMDOUBLECLICKDATA",UC.ParentObject.AV14ItemDoubleClickData); });
   QUERYVIEWER4Container.addV2CFunction('AV9DragAndDropData', "vDRAGANDDROPDATA", 'SetDragAndDropData');
   QUERYVIEWER4Container.addC2VFunction(function(UC) { UC.ParentObject.AV9DragAndDropData=UC.GetDragAndDropData();gx.fn.setControlValue("vDRAGANDDROPDATA",UC.ParentObject.AV9DragAndDropData); });
   QUERYVIEWER4Container.addV2CFunction('AV12FilterChangedData', "vFILTERCHANGEDDATA", 'SetFilterChangedData');
   QUERYVIEWER4Container.addC2VFunction(function(UC) { UC.ParentObject.AV12FilterChangedData=UC.GetFilterChangedData();gx.fn.setControlValue("vFILTERCHANGEDDATA",UC.ParentObject.AV12FilterChangedData); });
   QUERYVIEWER4Container.addV2CFunction('AV10ItemExpandData', "vITEMEXPANDDATA", 'SetItemExpandData');
   QUERYVIEWER4Container.addC2VFunction(function(UC) { UC.ParentObject.AV10ItemExpandData=UC.GetItemExpandData();gx.fn.setControlValue("vITEMEXPANDDATA",UC.ParentObject.AV10ItemExpandData); });
   QUERYVIEWER4Container.addV2CFunction('AV11ItemCollapseData', "vITEMCOLLAPSEDATA", 'SetItemCollapseData');
   QUERYVIEWER4Container.addC2VFunction(function(UC) { UC.ParentObject.AV11ItemCollapseData=UC.GetItemCollapseData();gx.fn.setControlValue("vITEMCOLLAPSEDATA",UC.ParentObject.AV11ItemCollapseData); });
   QUERYVIEWER4Container.setProp("AppSettings", "Appsettings", "", "char");
   QUERYVIEWER4Container.setProp("AvoidAutomaticShow", "Avoidautomaticshow", false, "boolean");
   QUERYVIEWER4Container.setProp("ExecuteShow", "Executeshow", false, "boolean");
   QUERYVIEWER4Container.setProp("ServiceUrl", "Serviceurl", "", "char");
   QUERYVIEWER4Container.setProp("GenType", "Gentype", "", "char");
   QUERYVIEWER4Container.setProp("DesignRenderOutputType", "Designrenderoutputtype", "", "char");
   QUERYVIEWER4Container.setProp("Visible", "Visible", true, "bool");
   QUERYVIEWER4Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(QUERYVIEWER4Container);
   this.QUERYVIEWER5Container = gx.uc.getNew(this, 18, 0, "QueryViewer", "QUERYVIEWER5Container", "Queryviewer5", "QUERYVIEWER5");
   var QUERYVIEWER5Container = this.QUERYVIEWER5Container;
   QUERYVIEWER5Container.setProp("Enabled", "Enabled", true, "boolean");
   QUERYVIEWER5Container.setProp("ObjectId", "Objectid", "14", "str");
   QUERYVIEWER5Container.setProp("ObjectType", "Objecttype", "Query", "str");
   QUERYVIEWER5Container.setProp("QueryInfo", "Queryinfo", "", "char");
   QUERYVIEWER5Container.setProp("IsExternalQuery", "Isexternalquery", false, "boolean");
   QUERYVIEWER5Container.setProp("ExternalQueryResult", "Externalqueryresult", "", "char");
   QUERYVIEWER5Container.setProp("ObjectInfo", "Objectinfo", "", "char");
   QUERYVIEWER5Container.addV2CFunction('AV7Axes', "vAXES", 'SetAxes');
   QUERYVIEWER5Container.addC2VFunction(function(UC) { UC.ParentObject.AV7Axes=UC.GetAxes();gx.fn.setControlValue("vAXES",UC.ParentObject.AV7Axes); });
   QUERYVIEWER5Container.setProp("AllowChangeAxesOrder", "Allowchangeaxesorder", false, "bool");
   QUERYVIEWER5Container.addV2CFunction('AV5Parameters', "vPARAMETERS", 'SetParameters');
   QUERYVIEWER5Container.addC2VFunction(function(UC) { UC.ParentObject.AV5Parameters=UC.GetParameters();gx.fn.setControlValue("vPARAMETERS",UC.ParentObject.AV5Parameters); });
   QUERYVIEWER5Container.setProp("ObjectName", "Objectname", "QColumnChart", "str");
   QUERYVIEWER5Container.setProp("Object", "Objectcall", "", "str");
   QUERYVIEWER5Container.setProp("Class", "Class", "QueryViewer", "str");
   QUERYVIEWER5Container.setProp("ShrinkToFit", "Shrinktofit", false, "boolean");
   QUERYVIEWER5Container.setProp("AutoResize", "Autoresize", false, "boolean");
   QUERYVIEWER5Container.setProp("AutoResizeType", "Autoresizetype", "", "char");
   QUERYVIEWER5Container.setProp("Width", "Width", "100%", "str");
   QUERYVIEWER5Container.setProp("Height", "Height", "100%", "str");
   QUERYVIEWER5Container.setProp("Axes Selectors", "Showaxesselectors", "", "char");
   QUERYVIEWER5Container.setProp("FontFamily", "Fontfamily", "", "char");
   QUERYVIEWER5Container.setProp("FontSize", "Fontsize", '', "int");
   QUERYVIEWER5Container.setProp("FontColor", "Fontcolor", '', "int");
   QUERYVIEWER5Container.setProp("AutoRefreshGroup", "Autorefreshgroup", "", "str");
   QUERYVIEWER5Container.setProp("DisableColumnSort", "Disablecolumnsort", false, "boolean");
   QUERYVIEWER5Container.setProp("AllowSelection", "Allowselection", false, "bool");
   QUERYVIEWER5Container.setProp("RememberLayout", "Rememberlayout", true, "bool");
   QUERYVIEWER5Container.setProp("ExportToXML", "Exporttoxml", true, "bool");
   QUERYVIEWER5Container.setProp("ExportToHTML", "Exporttohtml", true, "bool");
   QUERYVIEWER5Container.setProp("ExportToXLS", "Exporttoxls", true, "bool");
   QUERYVIEWER5Container.setProp("ExportToXLSX", "Exporttoxlsx", true, "bool");
   QUERYVIEWER5Container.setProp("ExportToPDF", "Exporttopdf", true, "bool");
   QUERYVIEWER5Container.setProp("Type", "Type", "Chart", "str");
   QUERYVIEWER5Container.setProp("ShowDataAs", "Showdataas", "", "char");
   QUERYVIEWER5Container.setProp("Orientation", "Orientation", "", "char");
   QUERYVIEWER5Container.setProp("IncludeTrend", "Includetrend", false, "boolean");
   QUERYVIEWER5Container.setProp("TrendPeriod", "Trendperiod", "", "char");
   QUERYVIEWER5Container.setProp("IncludeSparkline", "Includesparkline", false, "boolean");
   QUERYVIEWER5Container.setProp("IncludeMaxAndMin", "Includemaxandmin", false, "boolean");
   QUERYVIEWER5Container.setProp("ChartType", "Charttype", "Column", "str");
   QUERYVIEWER5Container.setProp("Title", "Title", "", "str");
   QUERYVIEWER5Container.setProp("PlotSeries", "Plotseries", "InTheSameChart", "str");
   QUERYVIEWER5Container.setProp("ShowValues", "Showvalues", true, "bool");
   QUERYVIEWER5Container.setProp("XAxisLabels", "Xaxislabels", "Horizontally", "str");
   QUERYVIEWER5Container.setProp("XAxisIntersectionAtZero", "Xaxisintersectionatzero", true, "bool");
   QUERYVIEWER5Container.setProp("XAxisTitle", "Xaxistitle", "RFM", "str");
   QUERYVIEWER5Container.setProp("YAxisTitle", "Yaxistitle", "Clientes", "str");
   QUERYVIEWER5Container.setProp("Paging", "Paging", false, "boolean");
   QUERYVIEWER5Container.setProp("PageSize", "Pagesize", '', "int");
   QUERYVIEWER5Container.setProp("CurrentPage", "Currentpage", '', "int");
   QUERYVIEWER5Container.setProp("ShowDataLabelsIn", "Showdatalabelsin", "", "char");
   QUERYVIEWER5Container.addV2CFunction('AV13ItemClickData', "vITEMCLICKDATA", 'SetItemClickData');
   QUERYVIEWER5Container.addC2VFunction(function(UC) { UC.ParentObject.AV13ItemClickData=UC.GetItemClickData();gx.fn.setControlValue("vITEMCLICKDATA",UC.ParentObject.AV13ItemClickData); });
   QUERYVIEWER5Container.addV2CFunction('AV14ItemDoubleClickData', "vITEMDOUBLECLICKDATA", 'SetItemDoubleClickData');
   QUERYVIEWER5Container.addC2VFunction(function(UC) { UC.ParentObject.AV14ItemDoubleClickData=UC.GetItemDoubleClickData();gx.fn.setControlValue("vITEMDOUBLECLICKDATA",UC.ParentObject.AV14ItemDoubleClickData); });
   QUERYVIEWER5Container.addV2CFunction('AV9DragAndDropData', "vDRAGANDDROPDATA", 'SetDragAndDropData');
   QUERYVIEWER5Container.addC2VFunction(function(UC) { UC.ParentObject.AV9DragAndDropData=UC.GetDragAndDropData();gx.fn.setControlValue("vDRAGANDDROPDATA",UC.ParentObject.AV9DragAndDropData); });
   QUERYVIEWER5Container.addV2CFunction('AV12FilterChangedData', "vFILTERCHANGEDDATA", 'SetFilterChangedData');
   QUERYVIEWER5Container.addC2VFunction(function(UC) { UC.ParentObject.AV12FilterChangedData=UC.GetFilterChangedData();gx.fn.setControlValue("vFILTERCHANGEDDATA",UC.ParentObject.AV12FilterChangedData); });
   QUERYVIEWER5Container.addV2CFunction('AV10ItemExpandData', "vITEMEXPANDDATA", 'SetItemExpandData');
   QUERYVIEWER5Container.addC2VFunction(function(UC) { UC.ParentObject.AV10ItemExpandData=UC.GetItemExpandData();gx.fn.setControlValue("vITEMEXPANDDATA",UC.ParentObject.AV10ItemExpandData); });
   QUERYVIEWER5Container.addV2CFunction('AV11ItemCollapseData', "vITEMCOLLAPSEDATA", 'SetItemCollapseData');
   QUERYVIEWER5Container.addC2VFunction(function(UC) { UC.ParentObject.AV11ItemCollapseData=UC.GetItemCollapseData();gx.fn.setControlValue("vITEMCOLLAPSEDATA",UC.ParentObject.AV11ItemCollapseData); });
   QUERYVIEWER5Container.setProp("AppSettings", "Appsettings", "", "char");
   QUERYVIEWER5Container.setProp("AvoidAutomaticShow", "Avoidautomaticshow", false, "boolean");
   QUERYVIEWER5Container.setProp("ExecuteShow", "Executeshow", false, "boolean");
   QUERYVIEWER5Container.setProp("ServiceUrl", "Serviceurl", "", "char");
   QUERYVIEWER5Container.setProp("GenType", "Gentype", "", "char");
   QUERYVIEWER5Container.setProp("DesignRenderOutputType", "Designrenderoutputtype", "", "char");
   QUERYVIEWER5Container.setProp("Visible", "Visible", true, "bool");
   QUERYVIEWER5Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(QUERYVIEWER5Container);
   this.QUERYVIEWER6Container = gx.uc.getNew(this, 20, 0, "QueryViewer", "QUERYVIEWER6Container", "Queryviewer6", "QUERYVIEWER6");
   var QUERYVIEWER6Container = this.QUERYVIEWER6Container;
   QUERYVIEWER6Container.setProp("Enabled", "Enabled", true, "boolean");
   QUERYVIEWER6Container.setProp("ObjectId", "Objectid", "16", "str");
   QUERYVIEWER6Container.setProp("ObjectType", "Objecttype", "Query", "str");
   QUERYVIEWER6Container.setProp("QueryInfo", "Queryinfo", "", "char");
   QUERYVIEWER6Container.setProp("IsExternalQuery", "Isexternalquery", false, "boolean");
   QUERYVIEWER6Container.setProp("ExternalQueryResult", "Externalqueryresult", "", "char");
   QUERYVIEWER6Container.setProp("ObjectInfo", "Objectinfo", "", "char");
   QUERYVIEWER6Container.addV2CFunction('AV7Axes', "vAXES", 'SetAxes');
   QUERYVIEWER6Container.addC2VFunction(function(UC) { UC.ParentObject.AV7Axes=UC.GetAxes();gx.fn.setControlValue("vAXES",UC.ParentObject.AV7Axes); });
   QUERYVIEWER6Container.setProp("AllowChangeAxesOrder", "Allowchangeaxesorder", false, "bool");
   QUERYVIEWER6Container.addV2CFunction('AV5Parameters', "vPARAMETERS", 'SetParameters');
   QUERYVIEWER6Container.addC2VFunction(function(UC) { UC.ParentObject.AV5Parameters=UC.GetParameters();gx.fn.setControlValue("vPARAMETERS",UC.ParentObject.AV5Parameters); });
   QUERYVIEWER6Container.setProp("ObjectName", "Objectname", "QTableChart1", "str");
   QUERYVIEWER6Container.setProp("Object", "Objectcall", "", "str");
   QUERYVIEWER6Container.setProp("Class", "Class", "QueryViewer", "str");
   QUERYVIEWER6Container.setProp("ShrinkToFit", "Shrinktofit", false, "boolean");
   QUERYVIEWER6Container.setProp("AutoResize", "Autoresize", false, "bool");
   QUERYVIEWER6Container.setProp("AutoResizeType", "Autoresizetype", "", "char");
   QUERYVIEWER6Container.setProp("Width", "Width", "100%", "str");
   QUERYVIEWER6Container.setProp("Height", "Height", "100%", "str");
   QUERYVIEWER6Container.setProp("Axes Selectors", "Showaxesselectors", "", "char");
   QUERYVIEWER6Container.setProp("FontFamily", "Fontfamily", "", "char");
   QUERYVIEWER6Container.setProp("FontSize", "Fontsize", '', "int");
   QUERYVIEWER6Container.setProp("FontColor", "Fontcolor", '', "int");
   QUERYVIEWER6Container.setProp("AutoRefreshGroup", "Autorefreshgroup", "", "str");
   QUERYVIEWER6Container.setProp("DisableColumnSort", "Disablecolumnsort", false, "bool");
   QUERYVIEWER6Container.setProp("AllowSelection", "Allowselection", false, "bool");
   QUERYVIEWER6Container.setProp("RememberLayout", "Rememberlayout", true, "bool");
   QUERYVIEWER6Container.setProp("ExportToXML", "Exporttoxml", true, "bool");
   QUERYVIEWER6Container.setProp("ExportToHTML", "Exporttohtml", true, "bool");
   QUERYVIEWER6Container.setProp("ExportToXLS", "Exporttoxls", true, "bool");
   QUERYVIEWER6Container.setProp("ExportToXLSX", "Exporttoxlsx", true, "bool");
   QUERYVIEWER6Container.setProp("ExportToPDF", "Exporttopdf", true, "bool");
   QUERYVIEWER6Container.setProp("Type", "Type", "Table", "str");
   QUERYVIEWER6Container.setProp("ShowDataAs", "Showdataas", "", "char");
   QUERYVIEWER6Container.setProp("Orientation", "Orientation", "", "char");
   QUERYVIEWER6Container.setProp("IncludeTrend", "Includetrend", false, "boolean");
   QUERYVIEWER6Container.setProp("TrendPeriod", "Trendperiod", "", "char");
   QUERYVIEWER6Container.setProp("IncludeSparkline", "Includesparkline", false, "boolean");
   QUERYVIEWER6Container.setProp("IncludeMaxAndMin", "Includemaxandmin", false, "boolean");
   QUERYVIEWER6Container.setProp("ChartType", "Charttype", "", "char");
   QUERYVIEWER6Container.setProp("Title", "Title", "", "char");
   QUERYVIEWER6Container.setProp("PlotSeries", "Plotseries", "", "char");
   QUERYVIEWER6Container.setProp("ShowValues", "Showvalues", false, "boolean");
   QUERYVIEWER6Container.setProp("XAxisLabels", "Xaxislabels", "", "char");
   QUERYVIEWER6Container.setProp("XAxisIntersectionAtZero", "Xaxisintersectionatzero", false, "boolean");
   QUERYVIEWER6Container.setProp("XAxisTitle", "Xaxistitle", "", "char");
   QUERYVIEWER6Container.setProp("YAxisTitle", "Yaxistitle", "", "char");
   QUERYVIEWER6Container.setProp("Paging", "Paging", true, "bool");
   QUERYVIEWER6Container.setProp("PageSize", "Pagesize", 20, "num");
   QUERYVIEWER6Container.setProp("CurrentPage", "Currentpage", '', "int");
   QUERYVIEWER6Container.setProp("ShowDataLabelsIn", "Showdatalabelsin", "", "char");
   QUERYVIEWER6Container.addV2CFunction('AV13ItemClickData', "vITEMCLICKDATA", 'SetItemClickData');
   QUERYVIEWER6Container.addC2VFunction(function(UC) { UC.ParentObject.AV13ItemClickData=UC.GetItemClickData();gx.fn.setControlValue("vITEMCLICKDATA",UC.ParentObject.AV13ItemClickData); });
   QUERYVIEWER6Container.addV2CFunction('AV14ItemDoubleClickData', "vITEMDOUBLECLICKDATA", 'SetItemDoubleClickData');
   QUERYVIEWER6Container.addC2VFunction(function(UC) { UC.ParentObject.AV14ItemDoubleClickData=UC.GetItemDoubleClickData();gx.fn.setControlValue("vITEMDOUBLECLICKDATA",UC.ParentObject.AV14ItemDoubleClickData); });
   QUERYVIEWER6Container.addV2CFunction('AV9DragAndDropData', "vDRAGANDDROPDATA", 'SetDragAndDropData');
   QUERYVIEWER6Container.addC2VFunction(function(UC) { UC.ParentObject.AV9DragAndDropData=UC.GetDragAndDropData();gx.fn.setControlValue("vDRAGANDDROPDATA",UC.ParentObject.AV9DragAndDropData); });
   QUERYVIEWER6Container.addV2CFunction('AV12FilterChangedData', "vFILTERCHANGEDDATA", 'SetFilterChangedData');
   QUERYVIEWER6Container.addC2VFunction(function(UC) { UC.ParentObject.AV12FilterChangedData=UC.GetFilterChangedData();gx.fn.setControlValue("vFILTERCHANGEDDATA",UC.ParentObject.AV12FilterChangedData); });
   QUERYVIEWER6Container.addV2CFunction('AV10ItemExpandData', "vITEMEXPANDDATA", 'SetItemExpandData');
   QUERYVIEWER6Container.addC2VFunction(function(UC) { UC.ParentObject.AV10ItemExpandData=UC.GetItemExpandData();gx.fn.setControlValue("vITEMEXPANDDATA",UC.ParentObject.AV10ItemExpandData); });
   QUERYVIEWER6Container.addV2CFunction('AV11ItemCollapseData', "vITEMCOLLAPSEDATA", 'SetItemCollapseData');
   QUERYVIEWER6Container.addC2VFunction(function(UC) { UC.ParentObject.AV11ItemCollapseData=UC.GetItemCollapseData();gx.fn.setControlValue("vITEMCOLLAPSEDATA",UC.ParentObject.AV11ItemCollapseData); });
   QUERYVIEWER6Container.setProp("AppSettings", "Appsettings", "", "char");
   QUERYVIEWER6Container.setProp("AvoidAutomaticShow", "Avoidautomaticshow", false, "boolean");
   QUERYVIEWER6Container.setProp("ExecuteShow", "Executeshow", false, "boolean");
   QUERYVIEWER6Container.setProp("ServiceUrl", "Serviceurl", "", "char");
   QUERYVIEWER6Container.setProp("GenType", "Gentype", "", "char");
   QUERYVIEWER6Container.setProp("DesignRenderOutputType", "Designrenderoutputtype", "", "char");
   QUERYVIEWER6Container.setProp("Visible", "Visible", true, "bool");
   QUERYVIEWER6Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(QUERYVIEWER6Container);
   this.SANKEYContainer = gx.uc.getNew(this, 23, 0, "Version1_UCSankeyDiagram", "SANKEYContainer", "Sankey", "SANKEY");
   var SANKEYContainer = this.SANKEYContainer;
   SANKEYContainer.setProp("Class", "Class", "", "char");
   SANKEYContainer.setProp("Enabled", "Enabled", true, "boolean");
   SANKEYContainer.addV2CFunction('AV16Resumen', "vRESUMEN", 'setResumen');
   SANKEYContainer.addC2VFunction(function(UC) { UC.ParentObject.AV16Resumen=UC.getResumen();gx.fn.setControlValue("vRESUMEN",UC.ParentObject.AV16Resumen); });
   SANKEYContainer.setProp("ResumenCurrentIndex", "Resumencurrentindex", 0, "num");
   SANKEYContainer.setProp("Visible", "Visible", true, "bool");
   SANKEYContainer.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(SANKEYContainer);
   this.QUERYVIEWER7Container = gx.uc.getNew(this, 26, 0, "QueryViewer", "QUERYVIEWER7Container", "Queryviewer7", "QUERYVIEWER7");
   var QUERYVIEWER7Container = this.QUERYVIEWER7Container;
   QUERYVIEWER7Container.setProp("Enabled", "Enabled", true, "boolean");
   QUERYVIEWER7Container.setProp("ObjectId", "Objectid", "8", "str");
   QUERYVIEWER7Container.setProp("ObjectType", "Objecttype", "Query", "str");
   QUERYVIEWER7Container.setProp("QueryInfo", "Queryinfo", "", "char");
   QUERYVIEWER7Container.setProp("IsExternalQuery", "Isexternalquery", false, "boolean");
   QUERYVIEWER7Container.setProp("ExternalQueryResult", "Externalqueryresult", "", "char");
   QUERYVIEWER7Container.setProp("ObjectInfo", "Objectinfo", "", "char");
   QUERYVIEWER7Container.addV2CFunction('AV7Axes', "vAXES", 'SetAxes');
   QUERYVIEWER7Container.addC2VFunction(function(UC) { UC.ParentObject.AV7Axes=UC.GetAxes();gx.fn.setControlValue("vAXES",UC.ParentObject.AV7Axes); });
   QUERYVIEWER7Container.setProp("AllowChangeAxesOrder", "Allowchangeaxesorder", false, "bool");
   QUERYVIEWER7Container.addV2CFunction('AV5Parameters', "vPARAMETERS", 'SetParameters');
   QUERYVIEWER7Container.addC2VFunction(function(UC) { UC.ParentObject.AV5Parameters=UC.GetParameters();gx.fn.setControlValue("vPARAMETERS",UC.ParentObject.AV5Parameters); });
   QUERYVIEWER7Container.setProp("ObjectName", "Objectname", "QLineChartFac", "str");
   QUERYVIEWER7Container.setProp("Object", "Objectcall", "", "str");
   QUERYVIEWER7Container.setProp("Class", "Class", "QueryViewer", "str");
   QUERYVIEWER7Container.setProp("ShrinkToFit", "Shrinktofit", false, "boolean");
   QUERYVIEWER7Container.setProp("AutoResize", "Autoresize", false, "boolean");
   QUERYVIEWER7Container.setProp("AutoResizeType", "Autoresizetype", "", "char");
   QUERYVIEWER7Container.setProp("Width", "Width", "100%", "str");
   QUERYVIEWER7Container.setProp("Height", "Height", "100%", "str");
   QUERYVIEWER7Container.setProp("Axes Selectors", "Showaxesselectors", "", "char");
   QUERYVIEWER7Container.setProp("FontFamily", "Fontfamily", "", "char");
   QUERYVIEWER7Container.setProp("FontSize", "Fontsize", '', "int");
   QUERYVIEWER7Container.setProp("FontColor", "Fontcolor", '', "int");
   QUERYVIEWER7Container.setProp("AutoRefreshGroup", "Autorefreshgroup", "", "str");
   QUERYVIEWER7Container.setProp("DisableColumnSort", "Disablecolumnsort", false, "boolean");
   QUERYVIEWER7Container.setProp("AllowSelection", "Allowselection", false, "bool");
   QUERYVIEWER7Container.setProp("RememberLayout", "Rememberlayout", true, "bool");
   QUERYVIEWER7Container.setProp("ExportToXML", "Exporttoxml", true, "bool");
   QUERYVIEWER7Container.setProp("ExportToHTML", "Exporttohtml", true, "bool");
   QUERYVIEWER7Container.setProp("ExportToXLS", "Exporttoxls", true, "bool");
   QUERYVIEWER7Container.setProp("ExportToXLSX", "Exporttoxlsx", true, "bool");
   QUERYVIEWER7Container.setProp("ExportToPDF", "Exporttopdf", true, "bool");
   QUERYVIEWER7Container.setProp("Type", "Type", "Chart", "str");
   QUERYVIEWER7Container.setProp("ShowDataAs", "Showdataas", "", "char");
   QUERYVIEWER7Container.setProp("Orientation", "Orientation", "", "char");
   QUERYVIEWER7Container.setProp("IncludeTrend", "Includetrend", false, "boolean");
   QUERYVIEWER7Container.setProp("TrendPeriod", "Trendperiod", "", "char");
   QUERYVIEWER7Container.setProp("IncludeSparkline", "Includesparkline", false, "boolean");
   QUERYVIEWER7Container.setProp("IncludeMaxAndMin", "Includemaxandmin", false, "boolean");
   QUERYVIEWER7Container.setProp("ChartType", "Charttype", "Line", "str");
   QUERYVIEWER7Container.setProp("Title", "Title", "Facturación", "str");
   QUERYVIEWER7Container.setProp("PlotSeries", "Plotseries", "InTheSameChart", "str");
   QUERYVIEWER7Container.setProp("ShowValues", "Showvalues", false, "bool");
   QUERYVIEWER7Container.setProp("XAxisLabels", "Xaxislabels", "Horizontally", "str");
   QUERYVIEWER7Container.setProp("XAxisIntersectionAtZero", "Xaxisintersectionatzero", true, "bool");
   QUERYVIEWER7Container.setProp("XAxisTitle", "Xaxistitle", "", "str");
   QUERYVIEWER7Container.setProp("YAxisTitle", "Yaxistitle", "Facturación", "str");
   QUERYVIEWER7Container.setProp("Paging", "Paging", false, "boolean");
   QUERYVIEWER7Container.setProp("PageSize", "Pagesize", '', "int");
   QUERYVIEWER7Container.setProp("CurrentPage", "Currentpage", '', "int");
   QUERYVIEWER7Container.setProp("ShowDataLabelsIn", "Showdatalabelsin", "", "char");
   QUERYVIEWER7Container.addV2CFunction('AV13ItemClickData', "vITEMCLICKDATA", 'SetItemClickData');
   QUERYVIEWER7Container.addC2VFunction(function(UC) { UC.ParentObject.AV13ItemClickData=UC.GetItemClickData();gx.fn.setControlValue("vITEMCLICKDATA",UC.ParentObject.AV13ItemClickData); });
   QUERYVIEWER7Container.addV2CFunction('AV14ItemDoubleClickData', "vITEMDOUBLECLICKDATA", 'SetItemDoubleClickData');
   QUERYVIEWER7Container.addC2VFunction(function(UC) { UC.ParentObject.AV14ItemDoubleClickData=UC.GetItemDoubleClickData();gx.fn.setControlValue("vITEMDOUBLECLICKDATA",UC.ParentObject.AV14ItemDoubleClickData); });
   QUERYVIEWER7Container.addV2CFunction('AV9DragAndDropData', "vDRAGANDDROPDATA", 'SetDragAndDropData');
   QUERYVIEWER7Container.addC2VFunction(function(UC) { UC.ParentObject.AV9DragAndDropData=UC.GetDragAndDropData();gx.fn.setControlValue("vDRAGANDDROPDATA",UC.ParentObject.AV9DragAndDropData); });
   QUERYVIEWER7Container.addV2CFunction('AV12FilterChangedData', "vFILTERCHANGEDDATA", 'SetFilterChangedData');
   QUERYVIEWER7Container.addC2VFunction(function(UC) { UC.ParentObject.AV12FilterChangedData=UC.GetFilterChangedData();gx.fn.setControlValue("vFILTERCHANGEDDATA",UC.ParentObject.AV12FilterChangedData); });
   QUERYVIEWER7Container.addV2CFunction('AV10ItemExpandData', "vITEMEXPANDDATA", 'SetItemExpandData');
   QUERYVIEWER7Container.addC2VFunction(function(UC) { UC.ParentObject.AV10ItemExpandData=UC.GetItemExpandData();gx.fn.setControlValue("vITEMEXPANDDATA",UC.ParentObject.AV10ItemExpandData); });
   QUERYVIEWER7Container.addV2CFunction('AV11ItemCollapseData', "vITEMCOLLAPSEDATA", 'SetItemCollapseData');
   QUERYVIEWER7Container.addC2VFunction(function(UC) { UC.ParentObject.AV11ItemCollapseData=UC.GetItemCollapseData();gx.fn.setControlValue("vITEMCOLLAPSEDATA",UC.ParentObject.AV11ItemCollapseData); });
   QUERYVIEWER7Container.setProp("AppSettings", "Appsettings", "", "char");
   QUERYVIEWER7Container.setProp("AvoidAutomaticShow", "Avoidautomaticshow", false, "boolean");
   QUERYVIEWER7Container.setProp("ExecuteShow", "Executeshow", false, "boolean");
   QUERYVIEWER7Container.setProp("ServiceUrl", "Serviceurl", "", "char");
   QUERYVIEWER7Container.setProp("GenType", "Gentype", "", "char");
   QUERYVIEWER7Container.setProp("DesignRenderOutputType", "Designrenderoutputtype", "", "char");
   QUERYVIEWER7Container.setProp("Visible", "Visible", true, "bool");
   QUERYVIEWER7Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(QUERYVIEWER7Container);
   GXValidFnc[2]={ id: 2, fld:"",grid:0};
   GXValidFnc[3]={ id: 3, fld:"MAINTABLE",grid:0};
   GXValidFnc[4]={ id: 4, fld:"",grid:0};
   GXValidFnc[5]={ id: 5, fld:"",grid:0};
   GXValidFnc[7]={ id: 7, fld:"",grid:0};
   GXValidFnc[9]={ id: 9, fld:"",grid:0};
   GXValidFnc[10]={ id: 10, fld:"",grid:0};
   GXValidFnc[12]={ id: 12, fld:"",grid:0};
   GXValidFnc[14]={ id: 14, fld:"",grid:0};
   GXValidFnc[16]={ id: 16, fld:"",grid:0};
   GXValidFnc[17]={ id: 17, fld:"",grid:0};
   GXValidFnc[19]={ id: 19, fld:"",grid:0};
   GXValidFnc[21]={ id: 21, fld:"",grid:0};
   GXValidFnc[22]={ id: 22, fld:"",grid:0};
   GXValidFnc[24]={ id: 24, fld:"",grid:0};
   GXValidFnc[25]={ id: 25, fld:"",grid:0};
   this.AV7Axes = [ ] ;
   this.AV16Resumen = [ ] ;
   this.Events = {"e121h2_client": ["ENTER", true] ,"e131h2_client": ["CANCEL", true]};
   this.EvtParms["REFRESH"] = [[],[]];
   this.EvtParms["LOAD"] = [[],[]];
   this.Initialize( );
   this.setComponent({id: "COMPONENT1" ,GXClass: "version1.wcfiltros" , Prefix: "W0008" , lvl: 1 });
});
gx.wi( function() { gx.createParentObj(version1.webpanel1);});
